#!/bin/bash -e

# The file is based on contributors.sh found in https://github.com/vmware/govmomi/blob/main/scripts/contributors.sh

file="$(git rev-parse --show-toplevel)/CONTRIBUTORS"

cat <<EOF > "$file"
# People who have contributed to this repository.
#
# This script is generated by $(basename "$0")
#

# Special thanks to Noahbot team:
Birb <7443606+HeckerBirb@users.noreply.github.com>
clubby789 <jamie@hill-daniel.co.uk>
Emma Samms <emma@0xem.ma>
Khaotic <6080590+khaoticdude@users.noreply.github.com>
TheWeeknd <98106526+ToxicBiohazard@users.noreply.github.com>

EOF

git log --format='%aN <%aE>' | sort -uf >> "$file"
