services:
  db:
    image: mariadb:10.11.2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hackster
      MYSQL_USER: hackster
      MYSQL_PASSWORD: hackster
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  bot:
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: hackster
      MYSQL_USER: hackster
      MYSQL_PASSWORD: hackster

volumes:
  db_data:
