"""Change unban_time data type

Revision ID: 05c1d218bb76
Revises: 6948a2436536
Create Date: 2023-05-09 13:28:06.763604

"""
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = '05c1d218bb76'
down_revision = '6948a2436536'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='ban', column_name="unban_time",
        existing_type=mysql.INTEGER(display_width=11),
        type_=mysql.BIGINT(display_width=18),
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='ban', column_name="unban_time",
        existing_type=mysql.BIGINT(display_width=18),
        type_=mysql.INTEGER(display_width=11),
        nullable=False
    )
    # ### end Alembic commands ###
