"""Fix data types and name for moderator

Revision ID: 364592ce1c76
Revises: fa20029d0cfb
Create Date: 2023-04-09 03:02:09.959641

"""
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = '364592ce1c76'
down_revision = 'fa20029d0cfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='ban', column_name="moderator", new_column_name="moderator_id",
        type_=mysql.BIGINT(display_width=18), nullable=False
    )
    op.alter_column(
        table_name='infraction', column_name="moderator", new_column_name="moderator_id",
        type_=mysql.BIGINT(display_width=18), nullable=False
    )
    op.alter_column(
        table_name='mute', column_name="moderator", new_column_name="moderator_id",
        type_=mysql.BIGINT(display_width=18), nullable=False
    )
    op.alter_column(
        table_name='user_note', column_name="moderator", new_column_name="moderator_id",
        type_=mysql.BIGINT(display_width=18), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='ban', column_name="moderator_id", new_column_name="moderator",
        type_=mysql.VARCHAR(length=42), nullable=False
    )
    op.alter_column(
        table_name='infraction', column_name="moderator_id", new_column_name="moderator",
        type_=mysql.VARCHAR(length=42), nullable=False
    )
    op.alter_column(
        table_name='mute', column_name="moderator_id", new_column_name="moderator",
        type_=mysql.VARCHAR(length=42), nullable=False
    )
    op.alter_column(
        table_name='user_note', column_name="moderator_id", new_column_name="moderator",
        type_=mysql.VARCHAR(length=42), nullable=False
    )
    # ### end Alembic commands ###
