"""Align DB

Revision ID: 402666fa2440
Revises: 4fc1c39216c9
Create Date: 2026-04-03 17:49:17.151261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '402666fa2440'
down_revision = '4fc1c39216c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ban', 'unban_time',
               existing_type=mysql.BIGINT(display_width=18),
               type_=mysql.BIGINT(display_width=11, unsigned=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_ctf_id'), table_name='ctf')
    op.alter_column('htb_discord_link', 'account_identifier',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('htb_discord_link', 'discord_user_id',
               existing_type=mysql.VARCHAR(length=42),
               type_=mysql.BIGINT(display_width=18),
               nullable=False)
    op.alter_column('htb_discord_link', 'htb_user_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=mysql.BIGINT(),
               nullable=False)
    op.alter_column('mute', 'unmute_time',
               existing_type=mysql.BIGINT(display_width=18),
               type_=mysql.BIGINT(display_width=11, unsigned=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mute', 'unmute_time',
               existing_type=mysql.BIGINT(display_width=11, unsigned=True),
               type_=mysql.BIGINT(display_width=18),
               existing_nullable=False)
    op.alter_column('htb_discord_link', 'htb_user_id',
               existing_type=mysql.BIGINT(),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('htb_discord_link', 'discord_user_id',
               existing_type=mysql.BIGINT(display_width=18),
               type_=mysql.VARCHAR(length=42),
               nullable=True)
    op.alter_column('htb_discord_link', 'account_identifier',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_ctf_id'), 'ctf', ['id'], unique=False)
    op.alter_column('ban', 'unban_time',
               existing_type=mysql.BIGINT(display_width=11, unsigned=True),
               type_=mysql.BIGINT(display_width=18),
               existing_nullable=False)
    # ### end Alembic commands ###
