"""Rename InfractionRecord to Infraction

Revision ID: 5b0179a1f13f
Revises: a71c110d3654
Create Date: 2023-04-09 02:42:40.458214

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '5b0179a1f13f'
down_revision = 'a71c110d3654'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("infraction_record", "infraction")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("infraction", "infraction_record")
    # ### end Alembic commands ###
