"""Fix data types for user_id

Revision ID: 6948a2436536
Revises: 364592ce1c76
Create Date: 2023-04-09 03:09:31.265814

"""
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = '6948a2436536'
down_revision = '364592ce1c76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='ban', column_name="user_id", type_=mysql.BIGINT(display_width=18), nullable=False
    )
    op.alter_column(
        table_name='infraction', column_name="user_id", type_=mysql.BIGINT(display_width=18), nullable=False
    )
    op.alter_column(
        table_name='mute', column_name="user_id", type_=mysql.BIGINT(display_width=18), nullable=False
    )
    op.alter_column(
        table_name='user_note', column_name="user_id", type_=mysql.BIGINT(display_width=18), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='ban', column_name="user_id", type_=mysql.VARCHAR(length=42), nullable=False
    )
    op.alter_column(
        table_name='infraction', column_name="user_id", type_=mysql.VARCHAR(length=42), nullable=False
    )
    op.alter_column(
        table_name='mute', column_name="user_id", type_=mysql.VARCHAR(length=42), nullable=False
    )
    op.alter_column(
        table_name='user_note', column_name="user_id", type_=mysql.VARCHAR(length=42), nullable=False
    )
    # ### end Alembic commands ###
