"""Add htb_discord_link table

Revision ID: 714c54b442ec
Revises:
Create Date: 2022-09-01 16:46:43.166154

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "714c54b442ec"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "htb_discord_link",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_identifier", sa.VARCHAR(length=255), nullable=True),
        sa.Column("discord_user_id", sa.VARCHAR(length=42), nullable=True),
        sa.Column("htb_user_id", sa.VARCHAR(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("htb_discord_link")
    # ### end Alembic commands ###
