"""Add mute_record table

Revision ID: 953fc0c9158c
Revises: 49c63ed4411d
Create Date: 2022-09-01 17:09:27.270130

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "953fc0c9158c"
down_revision = "49c63ed4411d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mute_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", mysql.VARCHAR(length=42), nullable=False),
        sa.Column("reason", mysql.TEXT(), nullable=False),
        sa.Column("moderator", mysql.VARCHAR(length=42), nullable=False),
        sa.Column("unmute_time", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mute_record")
    # ### end Alembic commands ###
