"""Add dynamic_role table

Revision ID: 9aa21aede2ec
Revises: 402666fa2440
Create Date: 2026-04-03 17:52:08.412419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9aa21aede2ec'
down_revision = '402666fa2440'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynamic_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('discord_role_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('category', sa.Enum('RANK', 'SEASON', 'SUBSCRIPTION_LABS', 'SUBSCRIPTION_ACADEMY', 'CREATOR', 'POSITION', 'ACADEMY_CERT', 'JOINABLE', name='rolecategory'), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('cert_full_name', sa.String(length=128), nullable=True),
    sa.Column('cert_integer_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'category', name='uq_dynamic_role_key_category')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dynamic_role')
    # ### end Alembic commands ###
