"""Change unmute_time data type

Revision ID: a5f283a4cfde
Revises: 05c1d218bb76
Create Date: 2023-05-09 13:34:17.055796

"""
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5f283a4cfde'
down_revision = '05c1d218bb76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='mute', column_name="unmute_time",
        existing_type=mysql.INTEGER(display_width=11),
        type_=mysql.BIGINT(display_width=18),
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='mute', column_name="unmute_time",
        existing_type=mysql.BIGINT(display_width=18),
        type_=mysql.INTEGER(display_width=11),
        nullable=False
    )
    # ### end Alembic commands ###
