"""Add user_note table

Revision ID: b372d25359fd
Revises: 953fc0c9158c
Create Date: 2022-09-01 17:11:33.104212

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "b372d25359fd"
down_revision = "953fc0c9158c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_note",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", mysql.VARCHAR(length=42), nullable=False),
        sa.Column("note", mysql.TEXT(), nullable=False),
        sa.Column("moderator", mysql.VARCHAR(length=42), nullable=False),
        sa.Column("date", sa.DATE(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_note")
    # ### end Alembic commands ###
