"""Rename MuteRecord to Mute

Revision ID: fa20029d0cfb
Revises: 5b0179a1f13f
Create Date: 2023-04-09 02:45:50.844425

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fa20029d0cfb'
down_revision = '5b0179a1f13f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("mute_record", "mute")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("mute", "mute_record")
    # ### end Alembic commands ###
