name: Build & Push

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  set-environment:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_type == 'tag' && !contains(github.ref_name, '-rc') && 'production' || 'development' }}
    outputs:
      role: ${{ steps.vars.outputs.role }}
      repository: ${{ steps.vars.outputs.repository }}
    steps:
      - id: vars
        run: |
          echo "role=${{ vars.AWS_GITHUB_ROLE }}" >> "$GITHUB_OUTPUT"
          echo "repository=${{ vars.ECR_REPOSITORY }}" >> "$GITHUB_OUTPUT"

  build:
    needs: set-environment
    uses: hackthebox/workflows/.github/workflows/build-docker-image.yml@main
    with:
      ecr_enabled: true
      ecr_repository: ${{ needs.set-environment.outputs.repository }}
      ecr_role_arn: ${{ needs.set-environment.outputs.role }}
      environment_name: ${{ github.ref_type == 'tag' && !contains(github.ref_name, '-rc') && 'production' || 'development' }}
      runner: ubuntu-latest
      enable_dockerhub_login: false
    secrets: inherit
