name: Deploy

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  deploy:
    environment:
      name: ${{ (contains(github.ref, '-rc')) && 'development' || 'production' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      COMMITTER: ${{ github.actor }}
      DOCKER_IMAGE: ghcr.io/hackthebox/hackster:${{ github.sha }}
      LATEST_IMAGE: ghcr.io/hackthebox/hackster:latest
      CHANGE_CAUSE: ${{ github.run_number }}-${{ github.sha }}
      DEPLOYMENT_NAME: ${{ (contains(github.ref, '-rc')) && 'hackster-dev' || 'hackster' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: ${{ env.DOCKER_IMAGE }},${{ env.LATEST_IMAGE }}
      - name: Rollout release
        uses: makelarisjr/kubectl-action@v1
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: |
            set image deployment ${{ env.DEPLOYMENT_NAME }} hackster=${{ env.DOCKER_IMAGE }};
            kubectl annotate deployment ${{ env.DEPLOYMENT_NAME }} kubernetes.io/change-cause="${{ env.CHANGE_CAUSE }}";
